# Name of your site (displayed in the header)
name: "domain-template"

# Short bio or description (displayed in the header)
description: "Primary theme for all sites"

# site tagline
tagline: "Serve it!"

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: "https://avatars2.githubusercontent.com/u/43266386?s=200&v=4"

# full domain name IE: httmp://mysite.com
url:

# full URI IE: /mysite { Do not add trailing / }
baseurl: ""

# set site author
author:
  name: 
  site: 

# set gallery image url
gallery:
  enabled: false
  folder: "/images/gallery"

# github options
github:
  show: true
  repo: 
  user: 
  avatar: 
  forkme: true
  layout: left-top

# set url for the contact form
form:
  enabled: false
  type: "formspree"
  formspree:
    submit_url: "https://formspree.io/f"
    code: ""
  formmail:
    submit_url: ""
    recipient: "form-submission"
    subject: "domain-template Contact Form"
    title: "domain-template"
    env: "REMOTE_HOST,HTTP_USER_AGENT"
    return_link:
      url: "javascript: history.go(-1)"
      title: "Back to Main Page"
    fields:
      name: "Name"
      email: "Email"
      message: "Message"
      required: "Name,Email,Message"
    theme:
      background: "https://casjaysdev-sites.github.io/static.casjay.net/assets/images/bkg.png"
      bgcolor: "#000000"
      text_color: "#ffffff"
      link_color: "#ffffff"
      vlink_color: "#ffffff"
      alink_color: "#ffffff"

# only set one of columns t: set a custom theme - includes/themes
custom_theme:
  name: hacker
  columns: "3"
  footer: "casjays-footer.html"
  header: "casjays-header.html"
  nav:
    bar: true
    external: true
    internal: true
    top: "nav/top.html"
    left: "nav/sidebars/left.html"
    right: "nav/sidebars/right.html"

# set default timezone
timezone: America/New_York

# set locale
locale: "en"

# Seperator for the the excerps
excerpt_separator: "\n\n"

# Set social media urls
share-this:
  rss: true
  code: "5acc08103368f4001495b647"
  repo: "https://github.com/casjay-templates/domain-template"
  email:
  enabled:
    footer: true
    script: true

# Includes an icon for each username you enter
social-links:
  rss: true
  name: 
  github: 
  twitter: 
  facebook: 
  flickr: 
  instagram: 
  linkedin: 
  pinterest: 
  email: 
  show_social: true

# Verfication Settings
webmaster_verifications:
  google: 12345
  bing: 12345
  alexa: 12345
  yandex: 12345
  baidu: 12345

# Enable/Disable footer sections
options:
  ads: true
  blog: true
  legal: true
  clock: true
  piwik: true
  engine: true
  google: true
  discord: true
  eucookie: true
  sharethis: true
  rocketchat: true
  statcounter: true
  last_updated: true

# theme footer link
engine:
  url: https://github.com/casjay-templates/jekyll-site

# Blog settings
blog:
  enabled: true
  api:

# RSS Feed
feed:
  path: /rss.xml
  posts_limit: 20

# eu cookie
eucookie:
  enabled: true

# You can find your shortname on the Settings page of your Disqus account
disqus:
  enabled: true
  shortcode: casjay

# clock settings
clock:
  enabled: true
  url: "https://freesecure.timeanddate.com/clock/i7k2kmtc/n12/fn6/fs16/fc9ff/tc000/ftb/bas2/bat1/bacfff/pa8/tt0/tw1/th1/ta1/tb4"

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google:
  analytics: 

# Ads
ads:
  enabled: false
  google:
    format: auto
    slot:
    client:

# piwik code
piwik:
  prefix: https
  site_id:
  url:

# enable rocketchat
rocketchat:
  url:

discord:
  enable: true
  server: 
  channel: 
  horizontal: bottom
  vertical: left

statuscounter:
  id: 
  code: ef07ac24
  url: //c.statcounter.com/REPLACEID/0/ef07ac24/0/

# You don't need to change any of the configuration flags below !!
permalink: pretty

tag_page: "/blog/tags/"
category_page: "/blog/categories/"

# Setup collections
collections:
  posts:
    output: true
    permalink: "/blog/:year/:month/:day/:title/"
  tags:
    output: true
    permalink: "/blog/tags/:path/"
  docs:
    permalink: "/docs/:path/"
    output: true
  tutorials:
    output: true
    permalink: /howto/:name
  issues:
    output: true
    permalink: /issues/:name
  recipes:
    output: true
    permalink: /recipes/:name
  wiki:
    output: true
    permalink: /wiki/:name

redirect_from:
json: true

# Set defaults
defaults:
  - scope:
      path: _docs
      type: docs
    values:
      layout: docs
  - scope:
      path: _posts
      type: posts
    values:
      layout: posts
  - scope:
      path: images
      type: images
    values:
      layout: images

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  footnote_backlink: "&#x21A9;&#xFE0E;"
  syntax_highlighter_opts:
    css_class: "highlight"

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: expanded

jekyll_tidy:
  compress_html: true
  exclude: ["*.md"]

# Use the following plug-ins
plugins:
  - jemoji
  - kramdown
  - github-pages
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-analytics
  - jekyll-remote-include
  - jekyll-menus
  - jekyll-remote-theme

# Include folders and files
include:
  - _pages
  - images

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME
  - .keep
  - .gitkeep
  - casjaysdev-jekyll-theme.gemspec

# Change output to _docs
destination: ./_site

# webrick options
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
