# frozen_string_literal: true
ruby '>=3.0.0'

source "https://rubygems.org" 
gem 'jemoji', '>=0.10.2'
gem 'kramdown', '>=2.2'
gem 'github-pages', '>=200'
gem 'jekyll-avatar', '>=0.5.0'
gem 'jekyll-feed', '>=0.14.0'
gem 'jekyll-mentions', '>=1.6'
gem 'jekyll-redirect-from', '>=0.16.0'
gem 'jekyll-seo-tag', '>=2.0'
gem 'jekyll-gist', '>=1.5'
gem 'jekyll-coffeescript', '>=1.1.1'
gem 'jekyll-assets', '>=3.0'
gem 'jekyll-sitemap', '>=1.4'
gem 'jekyll-analytics', '>=0.1.14'
gem 'jekyll-remote-include', '>=1.0'
gem 'jekyll-menus', '>=0.6.1'
gem 'jekyll-remote-theme', '>=0.4.3'
gem 'jekyll-paginate', '>=1.1'
gem 'jekyll-tidy', '~> 0.2.2'
gem 'jekyll', '>=3.5', '<5.0'
gem 'bundler', '>1.17'
gem 'rake', '~>13.0', '>13.0.2'
gem 'sprockets', '~> 3.7', '>= 3.7.2'
gem 'casjaysdev-jekyll-theme', '>=0.1.7'
